image: python:3.9
variables:
  WORK_DIR: .
cache:
  key: '$CI_COMMIT_REF_SLUG'
stages:
  - deploy
Deploy:
  stage: deploy
  only:
    - deploy 
  tags:
    - team-11-runner 
  script:
    - docker stop backend || true 
    - docker system prune -af --volumes
    - docker build -t team-11-backend .
    - docker run -it -d --restart always --name backend -p 5000:5000 team-11-backend
    